#!D:\Winpython\basedir35\build\winpython-64bit-3.5.x.4\python-3.5.1.amd64\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.numba_entry import main

if __name__ == "__main__":
    main()
